const repairPrices = {
    mobile: {
      Apple: {
        "iPhone 15": {"Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
    },
        "iPhone 14": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "iPhone 13": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "iPhone 12": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "iPhone 11": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "iPhone SE (2022)": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "iPhone XR": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "iPhone XS": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "iPhone 8": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "iPhone 7": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
      },
      Samsung: {
          "Galaxy S24": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
          "Galaxy S23": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Galaxy S22": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Galaxy S21": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Galaxy S20": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Galaxy Note 20": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Galaxy Z Fold 5": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Galaxy Z Flip 5": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Galaxy A54": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Galaxy A34": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
      },
      Google: {
        "Pixel 8": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Pixel 7": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Pixel 6": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Pixel 5": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Pixel 4a": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Pixel 4": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Pixel 3a": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Pixel 3": {"Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
    },
        "Pixel 2": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
        "Pixel 1": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
     },
      },
      Huawei: {
        "P60 Pro": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
       },
        "P50 Pro": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
       },
        "P40 Pro": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
       },
        "Mate 50": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
       },
        "Mate 40": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
       },
        "Nova 11": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
       },
        "Nova 10": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
       },
        "Nova 9": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
       },
        "Y9 Prime": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
       },
        "Y7 Prime": { "Battery Drain": 65,
        "Screen Cracks": 160,
        "Touchscreen Not Working": 130,
        "Charging Issues": 85,
        "Overheating": 95,
        "Speaker/Microphone Problems": 68,
        "Camera Not Working": 105,
        "Water Damage": 230,
        "Software Issues": 58,
        "Network & Connectivity Issues": 78,
       },
      },
    },
  
    laptop: {
      Apple: {
        "MacBook Air M2": { "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "MacBook Pro 16 M2": { "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "MacBook Pro 14 M2": { "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "MacBook Air M1": { "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "MacBook Pro 13 M1": { "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "MacBook Pro 16 Intel": { "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "MacBook Pro 13 Intel": { "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "MacBook Air Intel": { "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "MacBook 12 Retina": { "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "MacBook Pro 15 Intel": { "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
      },
      Dell: {
        "XPS 15": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "XPS 13": {  "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
      },
        "Inspiron 15": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Inspiron 14": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Latitude 7420": {  "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
      },
        "Latitude 5520": {  "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
      },
        "Alienware m15": {  "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
      },
        "Alienware m17": {  "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
      },
        "Vostro 15": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Vostro 14": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
      },
      Microsoft: {
        "Surface Laptop 5": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Surface Laptop 4": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Surface Laptop 3": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Surface Pro 9": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
      },
        "Surface Pro 8": {  "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
      },
        "Surface Pro 7": {  "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
      },
        "Surface Book 3": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Surface Go 3": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Surface Studio 2": {  "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
      },
        "Surface Laptop Go": {  "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
      },
      },
    },
  
    tablet: {
      Apple: {
        "iPad Pro M2": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
      },
        "iPad Air M1": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
      },
        "iPad 10th Gen": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
      },
        "iPad 9th Gen": { "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "iPad Mini 6": { "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "iPad Pro 12.9 (2021)": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
      },
        "iPad Pro 11 (2021)": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
      },
        "iPad 8th Gen": { "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "iPad 7th Gen": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
      },
        "iPad 6th Gen": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
      },
      },
      Samsung: {
        "Galaxy Tab S9": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "Galaxy Tab S8": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "Galaxy Tab S7": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "Galaxy Tab S6": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "Galaxy Tab A8": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "Galaxy Tab A7": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
       },
        "Galaxy Tab S6 Lite": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
      },
        "Galaxy Tab S7 FE": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
      },
        "Galaxy Tab Active 4": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
      },
        "Galaxy Tab S5e": {  "Battery Drains Quickly": 100,
        "Screen Not Responding": 220,
        "Charging Port Issues": 90,
        "Overheating": 110,
        "WiFi Connection Problems": 80,
        "Speaker Not Working": 70,
        "Touch Not Registering": 150,
        "System Lagging": 120,
        "Camera Issues": 100,
        "Frozen Screen": 130,
      },
      },
      Microsoft: {
        "Surface Pro 9": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Surface Pro 8": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Surface Pro 7": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Surface Go 3": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Surface Go 2": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Surface Pro X": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Surface Pro 6": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Surface Pro 5": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Surface 3": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
        "Surface 2": { "Battery Drains Quickly": 100,
         "Screen Not Responding": 220,
         "Charging Port Issues": 90,
         "Overheating": 110,
         "WiFi Connection Problems": 80,
         "Speaker Not Working": 70,
         "Touch Not Registering": 150,
         "System Lagging": 120,
         "Camera Issues": 100,
         "Frozen Screen": 130,
       },
      },
    },
  };


  export default repairPrices